### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lstables** [laracasts/JS-Component-Playground#1]
Hi @JeffreyWay I would love to see your approach on a Vue component that as a couple of input fields and and upload a file, either an image or PDF.

**Comment by wprk** [comment]
Hey @lstables, you should check out the https://laracasts.com/series/lets-build-a-forum-with-laravel course. In particular episode 65 for image upload or maybe 91-93 for a Vue Form. The whole series is really good though.

**Comment by lstables** [comment]
Yeah, I forgot about that series. Thanks @wprk will revisit.
